# Generated by Django 3.2 on 2021-04-30 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('avatar', models.ImageField(upload_to='user_image/', verbose_name='Изображение')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='Адрес')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='user',
        ),
        migrations.AlterField(
            model_name='courier',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stuff', to=settings.AUTH_USER_MODEL),
        ),
    ]
