# Generated by Django 3.2 on 2021-04-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Количество товара')),
            ],
            options={
                'verbose_name': 'Заказ продукта',
                'verbose_name_plural': 'Заказы продуктов',
            },
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='orders',
            name='courier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_order', to='user.courier'),
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('1', 'New'), ('2', 'Courier appointed'), ('3', 'On the way'), ('4', 'Delivered'), ('5', 'Canceled')], default=1, max_length=100),
        ),
    ]
